### PR TITLE
Bug/fix sep

### LINKED ISSUE #127: Module not found error
**Describe the bug**
I received module not found ERROR for all the components from Kitchen sink example. I am running it in windows instance.

**To Reproduce**
1) DOwnloaded the project zip from github
2) EXtracted the aem-master
3) RAn yarn from the root and then yarn build
4) THen opened a new terminal from kitchen-sink example and ran the command yarn storybook
5) ERROR in G:/aem-master/aem-sb-js-core-components/src/jcr_root/apps/core/wcm/components/breadcrumb/v2/breadcrumb/.content.xml
Module not found: Error: Can't resolve 'G:aem-masteraem-sb-js-core-componentssrcjcr_rootappscorewcmcomponentreadcrumbreadcrumb/' in 'G:\aem-master\aem-sb-js-core-components\src\jcr_root\apps\core\wcm\components\breadcrumb\v2\breadcrumb'
 @ G:/aem-master/aem-sb-js-core-components/src/jcr_root/apps/core/wcm/components/breadcrumb/v2/breadcrumb/.content.xml 4:29-10:5
 @ G:/aem-master/aem-sb-js-core-components/components.js
 @ G:/aem-master/aem-sb-js-core-components/index.js
 @ ./.storybook/preview.js
 @ multi G:/aem-master/node_modules/@storybook/core/dist/server/common/polyfills.js G:/aem-master/node_modules/@storybook/core/dist/server/preview/globals.js G:/aem-master/node_modules/@storybook/addon-docs/dist/frameworks/common/config.js ./.storybook/preview.js G:/aem-master/node_modules/@storybook/addon-knobs/dist/preset/addDecorator.js ./.storybook/generated-entry.js (webpack)-hot-middleware/client.js?reload=true&quiet=false

ERROR in G:/aem-master/aem-sb-js-core-components/src/jcr_root/apps/core/wcm/components/breadcrumb/v2/breadcrumb/.content.xml
Module not found: Error: Can't resolve 'G:aem-masteraem-sb-js-core-componentssrcjcr_rootappscorewcmcomponentreadcrumbreadcrumb/breadcrumb.html' in 'G:\aem-master\aem-sb-js-core-components\src\jcr_root\apps\core\wcm\components\breadcrumb\v2\breadcrumb'
 @ G:/aem-master/aem-sb-js-core-components/src/jcr_root/apps/core/wcm/components/breadcrumb/v2/breadcrumb/.content.xml 14:19-148
 @ G:/aem-master/aem-sb-js-core-components/components.js
 @ G:/aem-master/aem-sb-js-core-components/index.js
 @ ./.storybook/preview.js
 @ multi G:/aem-master/node_modules/@storybook/core/dist/server/common/polyfills.js G:/aem-master/node_modules/@storybook/core/dist/server/preview/globals.js G:/aem-master/node_modules/@storybook/addon-docs/dist/frameworks/common/config.js ./.storybook/preview.js G:/aem-master/node_modules/@storybook/addon-knobs/dist/preset/addDecorator.js ./.storybook/generated-entry.js (webpack)-hot-middleware/client.js?reload=true&quiet=false

ERROR in G:/aem-master/aem-sb-js-core-components/src/jcr_root/apps/core/wcm/components/button/v1/button/.content.xml
Module not found: Error: Can't resolve 'G:aem-masteraem-sb-js-core-componentssrcjcr_rootappscorewcmcomponentuttonutton/' in 'G:\aem-master\aem-sb-js-core-components\src\jcr_root\apps\core\wcm\components\button\v1\button'
 @ G:/aem-master/aem-sb-js-core-components/src/jcr_root/apps/core/wcm/components/button/v1/button/.content.xml 4:29-10:5
 @ G:/aem-master/aem-sb-js-core-components/components.js
 @ G:/aem-master/aem-sb-js-core-components/index.js
 @ ./.storybook/preview.js
 @ multi G:/aem-master/node_modules/@storybook/core/dist/server/common/polyfills.js G:/aem-master/node_modules/@storybook/core/dist/server/preview/globals.js G:/aem-master/node_modules/@storybook/addon-docs/dist/frameworks/common/config.js ./.storybook/preview.js G:/aem-master/node_modules/@storybook/addon-knobs/dist/preset/addDecorator.js ./.storybook/generated-entry.js (webpack)-hot-middleware/client.js?reload=true&quiet=false

ERROR in G:/aem-master/aem-sb-js-core-components/src/jcr_root/apps/core/wcm/components/button/v1/button/.content.xml
Module not found: Error: Can't resolve 'G:aem-masteraem-sb-js-core-componentssrcjcr_rootappscorewcmcomponentuttonutton/button.html' in 'G:\aem-master\aem-sb-js-core-components\src\jcr_root\apps\core\wcm\components\button\v1\button'
 @ G:/aem-master/aem-sb-js-core-components/src/jcr_root/apps/core/wcm/components/button/v1/button/.content.xml 14:19-136
 @ G:/aem-master/aem-sb-js-core-components/components.js
 @ G:/aem-master/aem-sb-js-core-components/index.js
 @ ./.storybook/preview.js
 @ multi G:/aem-master/node_modules/@storybook/core/dist/server/common/polyfills.js G:/aem-master/node_modules/@storybook/core/dist/server/preview/globals.js G:/aem-master/node_modules/@storybook/addon-docs/dist/frameworks/common/config.js ./.storybook/preview.js G:/aem-master/node_modules/@storybook/addon-knobs/dist/preset/addDecorator.js ./.storybook/generated-entry.js (webpack)-hot-middleware/client.js?reload=true&quiet=false

ERROR in G:/aem-master/aem-sb-js-core-components/src/jcr_root/apps/core/wcm/components/tabs/v1/tabs/.content.xml
Module not found: Error: Can't resolve 'G:aem-masteraem-sb-js-core-componentssrcjcr_rootappscorewcmcomponents   abs1  abs/' in 'G:\aem-master\aem-sb-js-core-components\src\jcr_root\apps\core\wcm\components\tabs\v1\tabs'
 @ G:/aem-master/aem-sb-js-core-components/src/jcr_root/apps/core/wcm/components/tabs/v1/tabs/.content.xml 4:29-10:5
 @ G:/aem-master/aem-sb-js-core-components/components.js
 @ G:/aem-master/aem-sb-js-core-components/index.js
 @ ./.storybook/preview.js
 @ multi G:/aem-master/node_modules/@storybook/core/dist/server/common/polyfills.js G:/aem-master/node_modules/@storybook/core/dist/server/preview/globals.js G:/aem-master/node_modules/@storybook/addon-docs/dist/frameworks/common/config.js ./.storybook/preview.js G:/aem-master/node_modules/@storybook/addon-knobs/dist/preset/addDecorator.js ./.storybook/generated-entry.js (webpack)-hot-middleware/client.js?reload=true&quiet=false

ERROR in G:/aem-master/aem-sb-js-core-components/src/jcr_root/apps/core/wcm/components/tabs/v1/tabs/.content.xml
Module not found: Error: Can't resolve 'G:aem-masteraem-sb-js-core-componentssrcjcr_rootappscorewcmcomponents   abs1  abs/tabs.html' in 'G:\aem-master\aem-sb-js-core-components\src\jcr_root\apps\core\wcm\components\tabs\v1\tabs'
 @ G:/aem-master/aem-sb-js-core-components/src/jcr_root/apps/core/wcm/components/tabs/v1/tabs/.content.xml 14:19-130
 @ G:/aem-master/aem-sb-js-core-components/components.js
 @ G:/aem-master/aem-sb-js-core-components/index.js
 @ ./.storybook/preview.js
 @ multi G:/aem-master/node_modules/@storybook/core/dist/server/common/polyfills.js G:/aem-master/node_modules/@storybook/core/dist/server/preview/globals.js G:/aem-master/node_modules/@storybook/addon-docs/dist/frameworks/common/config.js ./.storybook/preview.js G:/aem-master/node_modules/@storybook/addon-knobs/dist/preset/addDecorator.js ./.storybook/generated-entry.js (webpack)-hot-middleware/client.js?reload=true&quiet=false

ERROR in G:/aem-master/aem-sb-js-core-components/src/jcr_root/apps/core/wcm/components/teaser/v1/teaser/.content.xml
Module not found: Error: Can't resolve 'G:aem-masteraem-sb-js-core-componentssrcjcr_rootappscorewcmcomponents   easer1
easer/' in 'G:\aem-master\aem-sb-js-core-components\src\jcr_root\apps\core\wcm\components\teaser\v1\teaser'
 @ G:/aem-master/aem-sb-js-core-components/src/jcr_root/apps/core/wcm/components/teaser/v1/teaser/.content.xml 4:29-10:5
 @ G:/aem-master/aem-sb-js-core-components/components.js
 @ G:/aem-master/aem-sb-js-core-components/index.js
 @ ./.storybook/preview.js
 @ multi G:/aem-master/node_modules/@storybook/core/dist/server/common/polyfills.js G:/aem-master/node_modules/@storybook/core/dist/server/preview/globals.js G:/aem-master/node_modules/@storybook/addon-docs/dist/frameworks/common/config.js ./.storybook/preview.js G:/aem-master/node_modules/@storybook/addon-knobs/dist/preset/addDecorator.js ./.storybook/generated-entry.js (webpack)-hot-middleware/client.js?reload=true&quiet=false

ERROR in G:/aem-master/aem-sb-js-core-components/src/jcr_root/apps/core/wcm/components/teaser/v1/teaser/.content.xml
Module not found: Error: Can't resolve 'G:aem-masteraem-sb-js-core-componentssrcjcr_rootappscorewcmcomponents   easer1
easer/teaser.html' in 'G:\aem-master\aem-sb-js-core-components\src\jcr_root\apps\core\wcm\components\teaser\v1\teaser'
 @ G:/aem-master/aem-sb-js-core-components/src/jcr_root/apps/core/wcm/components/teaser/v1/teaser/.content.xml 14:19-136
 @ G:/aem-master/aem-sb-js-core-components/components.js
 @ G:/aem-master/aem-sb-js-core-components/index.js
 @ ./.storybook/preview.js
 @ multi G:/aem-master/node_modules/@storybook/core/dist/server/common/polyfills.js G:/aem-master/node_modules/@storybook/core/dist/server/preview/globals.js G:/aem-master/node_modules/@storybook/addon-docs/dist/frameworks/common/config.js ./.storybook/preview.js G:/aem-master/node_modules/@storybook/addon-knobs/dist/preset/addDecorator.js ./.storybook/generated-entry.js (webpack)-hot-middleware/client.js?reload=true&quiet=false

ERROR in G:/aem-master/aem-sb-js-core-components/src/jcr_root/apps/core/wcm/components/text/v2/text/.content.xml
Module not found: Error: Can't resolve 'G:aem-masteraem-sb-js-core-componentssrcjcr_rootappscorewcmcomponents   ext2  ext/' in 'G:\aem-master\aem-sb-js-core-components\src\jcr_root\apps\core\wcm\components\text\v2\text'
 @ G:/aem-master/aem-sb-js-core-components/src/jcr_root/apps/core/wcm/components/text/v2/text/.content.xml 4:29-10:5
 @ G:/aem-master/aem-sb-js-core-components/components.js
 @ G:/aem-master/aem-sb-js-core-components/index.js
 @ ./.storybook/preview.js
 @ multi G:/aem-master/node_modules/@storybook/core/dist/server/common/polyfills.js G:/aem-master/node_modules/@storybook/core/dist/server/preview/globals.js G:/aem-master/node_modules/@storybook/addon-docs/dist/frameworks/common/config.js ./.storybook/preview.js G:/aem-master/node_modules/@storybook/addon-knobs/dist/preset/addDecorator.js ./.storybook/generated-entry.js (webpack)-hot-middleware/client.js?reload=true&quiet=false

ERROR in G:/aem-master/aem-sb-js-core-components/src/jcr_root/apps/core/wcm/components/text/v2/text/.content.xml
Module not found: Error: Can't resolve 'G:aem-masteraem-sb-js-core-componentssrcjcr_rootappscorewcmcomponents   ext2  ext/text.html' in 'G:\aem-master\aem-sb-js-core-components\src\jcr_root\apps\core\wcm\components\text\v2\text'
 @ G:/aem-master/aem-sb-js-core-components/src/jcr_root/apps/core/wcm/components/text/v2/text/.content.xml 14:19-130
 @ G:/aem-master/aem-sb-js-core-components/components.js
 @ G:/aem-master/aem-sb-js-core-components/index.js
 @ ./.storybook/preview.js
 @ multi G:/aem-master/node_modules/@storybook/core/dist/server/common/polyfills.js G:/aem-master/node_modules/@storybook/core/dist/server/preview/globals.js G:/aem-master/node_modules/@storybook/addon-docs/dist/frameworks/common/config.js ./.storybook/preview.js G:/aem-master/node_modules/@storybook/addon-knobs/dist/preset/addDecorator.js ./.storybook/generated-entry.js (webpack)-hot-middleware/client.js?reload=true&quiet=false

ERROR in G:/aem-master/aem-sb-js-core-components/src/jcr_root/apps/core/wcm/components/title/v2/title/.content.xml
Module not found: Error: Can't resolve 'G:aem-masteraem-sb-js-core-componentssrcjcr_rootappscorewcmcomponents   itle2 itle/' in 'G:\aem-master\aem-sb-js-core-components\src\jcr_root\apps\core\wcm\components\title\v2\title'
 @ G:/aem-master/aem-sb-js-core-components/src/jcr_root/apps/core/wcm/components/title/v2/title/.content.xml 4:29-10:5
 @ G:/aem-master/aem-sb-js-core-components/components.js
 @ G:/aem-master/aem-sb-js-core-components/index.js
 @ ./.storybook/preview.js
 @ multi G:/aem-master/node_modules/@storybook/core/dist/server/common/polyfills.js G:/aem-master/node_modules/@storybook/core/dist/server/preview/globals.js G:/aem-master/node_modules/@storybook/addon-docs/dist/frameworks/common/config.js ./.storybook/preview.js G:/aem-master/node_modules/@storybook/addon-knobs/dist/preset/addDecorator.js ./.storybook/generated-entry.js (webpack)-hot-middleware/client.js?reload=true&quiet=false

ERROR in G:/aem-master/aem-sb-js-core-components/src/jcr_root/apps/core/wcm/components/title/v2/title/.content.xml
Module not found: Error: Can't resolve 'G:aem-masteraem-sb-js-core-componentssrcjcr_rootappscorewcmcomponents   itle2 itle/title.html' in 'G:\aem-master\aem-sb-js-core-components\src\jcr_root\apps\core\wcm\components\title\v2\title'
 @ G:/aem-master/aem-sb-js-core-components/src/jcr_root/apps/core/wcm/components/title/v2/title/.content.xml 14:19-133
 @ G:/aem-master/aem-sb-js-core-components/components.js
 @ G:/aem-master/aem-sb-js-core-components/index.js
 @ ./.storybook/preview.js
 @ multi G:/aem-master/node_modules/@storybook/core/dist/server/common/polyfills.js G:/aem-master/node_modules/@storybook/core/dist/server/preview/globals.js G:/aem-master/node_modules/@storybook/addon-docs/dist/frameworks/common/config.js ./.storybook/preview.js G:/aem-master/node_modules/@storybook/addon-knobs/dist/preset/addDecorator.js ./.storybook/generated-entry.js (webpack)-hot-middleware/client.js?reload=true&quiet=false

ERROR in G:/aem-master/aem-sb-js-core-components/src/jcr_root/apps/core/wcm/components/form/button/v2/button/.content.xml
Module not found: Error: Can't resolve 'G:aem-masteraem-sb-js-core-componentssrcjcr_rootappscorewcmcomponentsoruttonutton/' in 'G:\aem-master\aem-sb-js-core-components\src\jcr_root\apps\core\wcm\components\form\button\v2\button'
 @ G:/aem-master/aem-sb-js-core-components/src/jcr_root/apps/core/wcm/components/form/button/v2/button/.content.xml 4:29-10:5
 @ G:/aem-master/aem-sb-js-core-components/components.js
 @ G:/aem-master/aem-sb-js-core-components/index.js
 @ ./.storybook/preview.js
 @ multi G:/aem-master/node_modules/@storybook/core/dist/server/common/polyfills.js G:/aem-master/node_modules/@storybook/core/dist/server/preview/globals.js G:/aem-master/node_modules/@storybook/addon-docs/dist/frameworks/common/config.js ./.storybook/preview.js G:/aem-master/node_modules/@storybook/addon-knobs/dist/preset/addDecorator.js ./.storybook/generated-entry.js (webpack)-hot-middleware/client.js?reload=true&quiet=false

ERROR in G:/aem-master/aem-sb-js-core-components/src/jcr_root/apps/core/wcm/components/form/button/v2/button/.content.xml
Module not found: Error: Can't resolve 'G:aem-masteraem-sb-js-core-componentssrcjcr_rootappscorewcmcomponentsoruttonutton/button.html' in 'G:\aem-master\aem-sb-js-core-components\src\jcr_root\apps\core\wcm\components\form\button\v2\button'
 @ G:/aem-master/aem-sb-js-core-components/src/jcr_root/apps/core/wcm/components/form/button/v2/button/.content.xml 14:19-141
 @ G:/aem-master/aem-sb-js-core-components/components.js
 @ G:/aem-master/aem-sb-js-core-components/index.js
 @ ./.storybook/preview.js
 @ multi G:/aem-master/node_modules/@storybook/core/dist/server/common/polyfills.js G:/aem-master/node_modules/@storybook/core/dist/server/preview/globals.js G:/aem-master/node_modules/@storybook/addon-docs/dist/frameworks/common/config.js ./.storybook/preview.js G:/aem-master/node_modules/@storybook/addon-knobs/dist/preset/addDecorator.js ./.storybook/generated-entry.js (webpack)-hot-middleware/client.js?reload=true&quiet=false

ERROR in G:/aem-master/aem-sb-js-core-components/src/jcr_root/apps/core/wcm/components/form/text/v2/text/.content.xml
Module not found: Error: Can't resolve 'G:aem-masteraem-sb-js-core-componentssrcjcr_rootappscorewcmcomponentsorm      ext2    ext/' in 'G:\aem-master\aem-sb-js-core-components\src\jcr_root\apps\core\wcm\components\form\text\v2\text'
 @ G:/aem-master/aem-sb-js-core-components/src/jcr_root/apps/core/wcm/components/form/text/v2/text/.content.xml 4:29-10:5
 @ G:/aem-master/aem-sb-js-core-components/components.js
 @ G:/aem-master/aem-sb-js-core-components/index.js
 @ ./.storybook/preview.js
 @ multi G:/aem-master/node_modules/@storybook/core/dist/server/common/polyfills.js G:/aem-master/node_modules/@storybook/core/dist/server/preview/globals.js G:/aem-master/node_modules/@storybook/addon-docs/dist/frameworks/common/config.js ./.storybook/preview.js G:/aem-master/node_modules/@storybook/addon-knobs/dist/preset/addDecorator.js ./.storybook/generated-entry.js (webpack)-hot-middleware/client.js?reload=true&quiet=false

ERROR in G:/aem-master/aem-sb-js-core-components/src/jcr_root/apps/core/wcm/components/form/text/v2/text/.content.xml
Module not found: Error: Can't resolve 'G:aem-masteraem-sb-js-core-componentssrcjcr_rootappscorewcmcomponentsorm      ext2    ext/text.html' in 'G:\aem-master\aem-sb-js-core-components\src\jcr_root\apps\core\wcm\components\form\text\v2\text'
 @ G:/aem-master/aem-sb-js-core-components/src/jcr_root/apps/core/wcm/components/form/text/v2/text/.content.xml 14:19-135
 @ G:/aem-master/aem-sb-js-core-components/components.js
 @ G:/aem-master/aem-sb-js-core-components/index.js
 @ ./.storybook/preview.js
 @ multi G:/aem-master/node_modules/@storybook/core/dist/server/common/polyfills.js G:/aem-master/node_modules/@storybook/core/dist/server/preview/globals.js G:/aem-master/node_modules/@storybook/addon-docs/dist/frameworks/common/config.js ./.storybook/preview.js G:/aem-master/node_modules/@storybook/addon-knobs/dist/preset/addDecorator.js ./.storybook/generated-entry.js (webpack)-hot-middleware/client.js?reload=true&quiet=false

ERROR in G:/aem-master/aem-sb-js-core-components/src/jcr_root/apps/core/wcm/components/accordion/v1/accordion/.content.xml
Module not found: Error: Can't resolve 'G:aem-masteraem-sb-js-core-componentssrcjcr_rootappscorewcmcomponentsaccordion1accordion/' in 'G:\aem-master\aem-sb-js-core-components\src\jcr_root\apps\core\wcm\components\accordion\v1\accordion'
 @ G:/aem-master/aem-sb-js-core-components/src/jcr_root/apps/core/wcm/components/accordion/v1/accordion/.content.xml 4:29-10:5
 @ G:/aem-master/aem-sb-js-core-components/components.js
 @ G:/aem-master/aem-sb-js-core-components/index.js
 @ ./.storybook/preview.js
 @ multi G:/aem-master/node_modules/@storybook/core/dist/server/common/polyfills.js G:/aem-master/node_modules/@storybook/core/dist/server/preview/globals.js G:/aem-master/node_modules/@storybook/addon-docs/dist/frameworks/common/config.js ./.storybook/preview.js G:/aem-master/node_modules/@storybook/addon-knobs/dist/preset/addDecorator.js ./.storybook/generated-entry.js (webpack)-hot-middleware/client.js?reload=true&quiet=false

ERROR in G:/aem-master/aem-sb-js-core-components/src/jcr_root/apps/core/wcm/components/accordion/v1/accordion/.content.xml
Module not found: Error: Can't resolve 'G:aem-masteraem-sb-js-core-componentssrcjcr_rootappscorewcmcomponentsaccordion1accordion/accordion.html' in 'G:\aem-master\aem-sb-js-core-components\src\jcr_root\apps\core\wcm\components\accordion\v1\accordion'
 @ G:/aem-master/aem-sb-js-core-components/src/jcr_root/apps/core/wcm/components/accordion/v1/accordion/.content.xml 14:19-145
 @ G:/aem-master/aem-sb-js-core-components/components.js
 @ G:/aem-master/aem-sb-js-core-components/index.js
 @ ./.storybook/preview.js
 @ multi G:/aem-master/node_modules/@storybook/core/dist/server/common/polyfills.js G:/aem-master/node_modules/@storybook/core/dist/server/preview/globals.js G:/aem-master/node_modules/@storybook/addon-docs/dist/frameworks/common/config.js ./.storybook/preview.js G:/aem-master/node_modules/@storybook/addon-knobs/dist/preset/addDecorator.js ./.storybook/generated-entry.js (webpack)-hot-middleware/client.js?reload=true&quiet=false

ERROR in G:/aem-master/aem-sb-js-core-components/src/jcr_root/apps/core/wcm/components/image/v2/image/.content.xml
Module not found: Error: Can't resolve 'G:aem-masteraem-sb-js-core-componentssrcjcr_rootappscorewcmcomponentsimage2image/' in 'G:\aem-master\aem-sb-js-core-components\src\jcr_root\apps\core\wcm\components\image\v2\image'
 @ G:/aem-master/aem-sb-js-core-components/src/jcr_root/apps/core/wcm/components/image/v2/image/.content.xml 4:29-10:5
 @ G:/aem-master/aem-sb-js-core-components/components.js
 @ G:/aem-master/aem-sb-js-core-components/index.js
 @ ./.storybook/preview.js
 @ multi G:/aem-master/node_modules/@storybook/core/dist/server/common/polyfills.js G:/aem-master/node_modules/@storybook/core/dist/server/preview/globals.js G:/aem-master/node_modules/@storybook/addon-docs/dist/frameworks/common/config.js ./.storybook/preview.js G:/aem-master/node_modules/@storybook/addon-knobs/dist/preset/addDecorator.js ./.storybook/generated-entry.js (webpack)-hot-middleware/client.js?reload=true&quiet=false

ERROR in G:/aem-master/aem-sb-js-core-components/src/jcr_root/apps/core/wcm/components/image/v2/image/.content.xml
Module not found: Error: Can't resolve 'G:aem-masteraem-sb-js-core-componentssrcjcr_rootappscorewcmcomponentsimage2image/image.html' in 'G:\aem-master\aem-sb-js-core-components\src\jcr_root\apps\core\wcm\components\image\v2\image'
 @ G:/aem-master/aem-sb-js-core-components/src/jcr_root/apps/core/wcm/components/image/v2/image/.content.xml 14:19-133
 @ G:/aem-master/aem-sb-js-core-components/components.js
 @ G:/aem-master/aem-sb-js-core-components/index.js
 @ ./.storybook/preview.js
 @ multi G:/aem-master/node_modules/@storybook/core/dist/server/common/polyfills.js G:/aem-master/node_modules/@storybook/core/dist/server/preview/globals.js G:/aem-master/node_modules/@storybook/addon-docs/dist/frameworks/common/config.js ./.storybook/preview.js G:/aem-master/node_modules/@storybook/addon-knobs/dist/preset/addDecorator.js ./.storybook/generated-entry.js (webpack)-hot-middleware/client.js?reload=true&quiet=false

ERROR in G:/aem-master/aem-sb-js-core-components/src/jcr_root/apps/core/wcm/components/list/v2/list/.content.xml
Module not found: Error: Can't resolve 'G:aem-masteraem-sb-js-core-componentssrcjcr_rootappscorewcmcomponentslist2list/' in 'G:\aem-master\aem-sb-js-core-components\src\jcr_root\apps\core\wcm\components\list\v2\list'
 @ G:/aem-master/aem-sb-js-core-components/src/jcr_root/apps/core/wcm/components/list/v2/list/.content.xml 4:29-10:5
 @ G:/aem-master/aem-sb-js-core-components/components.js
 @ G:/aem-master/aem-sb-js-core-components/index.js
 @ ./.storybook/preview.js
 @ multi G:/aem-master/node_modules/@storybook/core/dist/server/common/polyfills.js G:/aem-master/node_modules/@storybook/core/dist/server/preview/globals.js G:/aem-master/node_modules/@storybook/addon-docs/dist/frameworks/common/config.js ./.storybook/preview.js G:/aem-master/node_modules/@storybook/addon-knobs/dist/preset/addDecorator.js ./.storybook/generated-entry.js (webpack)-hot-middleware/client.js?reload=true&quiet=false

ERROR in G:/aem-master/aem-sb-js-core-components/src/jcr_root/apps/core/wcm/components/list/v2/list/.content.xml
Module not found: Error: Can't resolve 'G:aem-masteraem-sb-js-core-componentssrcjcr_rootappscorewcmcomponentslist2list/list.html' in 'G:\aem-master\aem-sb-js-core-components\src\jcr_root\apps\core\wcm\components\list\v2\list'
 @ G:/aem-master/aem-sb-js-core-components/src/jcr_root/apps/core/wcm/components/list/v2/list/.content.xml 14:19-130
 @ G:/aem-master/aem-sb-js-core-components/components.js
 @ G:/aem-master/aem-sb-js-core-components/index.js
 @ ./.storybook/preview.js
 @ multi G:/aem-master/node_modules/@storybook/core/dist/server/common/polyfills.js G:/aem-master/node_modules/@storybook/core/dist/server/preview/globals.js G:/aem-master/node_modules/@storybook/addon-docs/dist/frameworks/common/config.js ./.storybook/preview.js G:/aem-master/node_modules/@storybook/addon-knobs/dist/preset/addDecorator.js ./.storybook/generated-entry.js (webpack)-hot-middleware/client.js?reload=true&quiet=false

ERROR in G:/aem-master/aem-sb-js-core-components/src/jcr_root/apps/core/wcm/components/progressbar/v1/progressbar/.content.xml
Module not found: Error: Can't resolve 'G:aem-masteraem-sb-js-core-componentssrcjcr_rootappscorewcmcomponentsprogressba1progressbar/' in 'G:\aem-master\aem-sb-js-core-components\src\jcr_root\apps\core\wcm\components\progressbar\v1\progressbar'
 @ G:/aem-master/aem-sb-js-core-components/src/jcr_root/apps/core/wcm/components/progressbar/v1/progressbar/.content.xml 4:29-10:5
 @ G:/aem-master/aem-sb-js-core-components/components.js
 @ G:/aem-master/aem-sb-js-core-components/index.js
 @ ./.storybook/preview.js
 @ multi G:/aem-master/node_modules/@storybook/core/dist/server/common/polyfills.js G:/aem-master/node_modules/@storybook/core/dist/server/preview/globals.js G:/aem-master/node_modules/@storybook/addon-docs/dist/frameworks/common/config.js ./.storybook/preview.js G:/aem-master/node_modules/@storybook/addon-knobs/dist/preset/addDecorator.js ./.storybook/generated-entry.js (webpack)-hot-middleware/client.js?reload=true&quiet=false

ERROR in G:/aem-master/aem-sb-js-core-components/src/jcr_root/apps/core/wcm/components/progressbar/v1/progressbar/.content.xml
Module not found: Error: Can't resolve 'G:aem-masteraem-sb-js-core-componentssrcjcr_rootappscorewcmcomponentsprogressba1progressbar/progressbar.html' in 'G:\aem-master\aem-sb-js-core-components\src\jcr_root\apps\core\wcm\components\progressbar\v1\progressbar'
 @ G:/aem-master/aem-sb-js-core-components/src/jcr_root/apps/core/wcm/components/progressbar/v1/progressbar/.content.xml 14:19-151
 @ G:/aem-master/aem-sb-js-core-components/components.js
 @ G:/aem-master/aem-sb-js-core-components/index.js
 @ ./.storybook/preview.js
 @ multi G:/aem-master/node_modules/@storybook/core/dist/server/common/polyfills.js G:/aem-master/node_modules/@storybook/core/dist/server/preview/globals.js G:/aem-master/node_modules/@storybook/addon-docs/dist/frameworks/common/config.js ./.storybook/preview.js G:/aem-master/node_modules/@storybook/addon-knobs/dist/preset/addDecorator.js ./.storybook/generated-entry.js (webpack)-hot-middleware/client.js?reload=true&quiet=false

ERROR in G:/aem-master/aem-sb-js-core-components/src/jcr_root/apps/core/wcm/components/separator/v1/separator/.content.xml
Module not found: Error: Can't resolve 'G:aem-masteraem-sb-js-core-componentssrcjcr_rootappscorewcmcomponentsseparator1separator/' in 'G:\aem-master\aem-sb-js-core-components\src\jcr_root\apps\core\wcm\components\separator\v1\separator'
 @ G:/aem-master/aem-sb-js-core-components/src/jcr_root/apps/core/wcm/components/separator/v1/separator/.content.xml 4:29-10:5
 @ G:/aem-master/aem-sb-js-core-components/components.js
 @ G:/aem-master/aem-sb-js-core-components/index.js
 @ ./.storybook/preview.js
 @ multi G:/aem-master/node_modules/@storybook/core/dist/server/common/polyfills.js G:/aem-master/node_modules/@storybook/core/dist/server/preview/globals.js G:/aem-master/node_modules/@storybook/addon-docs/dist/frameworks/common/config.js ./.storybook/preview.js G:/aem-master/node_modules/@storybook/addon-knobs/dist/preset/addDecorator.js ./.storybook/generated-entry.js (webpack)-hot-middleware/client.js?reload=true&quiet=false

ERROR in G:/aem-master/aem-sb-js-core-components/src/jcr_root/apps/core/wcm/components/separator/v1/separator/.content.xml
Module not found: Error: Can't resolve 'G:aem-masteraem-sb-js-core-componentssrcjcr_rootappscorewcmcomponentsseparator1separator/separator.html' in 'G:\aem-master\aem-sb-js-core-components\src\jcr_root\apps\core\wcm\components\separator\v1\separator'
 @ G:/aem-master/aem-sb-js-core-components/src/jcr_root/apps/core/wcm/components/separator/v1/separator/.content.xml 14:19-145
 @ G:/aem-master/aem-sb-js-core-components/components.js
 @ G:/aem-master/aem-sb-js-core-components/index.js
 @ ./.storybook/preview.js
 @ multi G:/aem-master/node_modules/@storybook/core/dist/server/common/polyfills.js G:/aem-master/node_modules/@storybook/core/dist/server/preview/globals.js G:/aem-master/node_modules/@storybook/addon-docs/dist/frameworks/common/config.js ./.storybook/preview.js G:/aem-master/node_modules/@storybook/addon-knobs/dist/preset/addDecorator.js ./.storybook/generated-entry.js (webpack)-hot-middleware/client.js?reload=true&quiet=false

ERROR in ./components/text/.content.xml
Module not found: Error: Can't resolve 'G:aem-masterexamplesaem-kitchen-sinkcomponents  ext/' in 'G:\aem-master\examples\aem-kitchen-sink\components\text'
 @ ./components/text/.content.xml 4:29-10:5
 @ ./.storybook/preview.js
 @ multi G:/aem-master/node_modules/@storybook/core/dist/server/common/polyfills.js G:/aem-master/node_modules/@storybook/core/dist/server/preview/globals.js G:/aem-master/node_modules/@storybook/addon-docs/dist/frameworks/common/config.js ./.storybook/preview.js G:/aem-master/node_modules/@storybook/addon-knobs/dist/preset/addDecorator.js ./.storybook/generated-entry.js (webpack)-hot-middleware/client.js?reload=true&quiet=false

ERROR in ./components/text/.content.xml
Module not found: Error: Can't resolve 'G:aem-masterexamplesaem-kitchen-sinkcomponents  ext/text.html' in 'G:\aem-master\examples\aem-kitchen-sink\components\text'
 @ ./components/text/.content.xml 14:19-95
 @ ./.storybook/preview.js
 @ multi G:/aem-master/node_modules/@storybook/core/dist/server/common/polyfills.js G:/aem-master/node_modules/@storybook/core/dist/server/preview/globals.js G:/aem-master/node_modules/@storybook/addon-docs/dist/frameworks/common/config.js ./.storybook/preview.js G:/aem-master/node_modules/@storybook/addon-knobs/dist/preset/addDecorator.js ./.storybook/generated-entry.js (webpack)-hot-middleware/client.js?reload=true&quiet=false

ERROR in ./components/accordion/.content.xml
Module not found: Error: Can't resolve 'G:aem-masterexamplesaem-kitchen-sinkcomponentsaccordion/' in 'G:\aem-master\examples\aem-kitchen-sink\components\accordion'
 @ ./components/accordion/.content.xml 4:29-10:5
 @ ./.storybook/preview.js
 @ multi G:/aem-master/node_modules/@storybook/core/dist/server/common/polyfills.js G:/aem-master/node_modules/@storybook/core/dist/server/preview/globals.js G:/aem-master/node_modules/@storybook/addon-docs/dist/frameworks/common/config.js ./.storybook/preview.js G:/aem-master/node_modules/@storybook/addon-knobs/dist/preset/addDecorator.js ./.storybook/generated-entry.js (webpack)-hot-middleware/client.js?reload=true&quiet=false

ERROR in ./components/accordion/.content.xml
Module not found: Error: Can't resolve 'G:aem-masterexamplesaem-kitchen-sinkcomponentsaccordion/accordion.html' in 'G:\aem-master\examples\aem-kitchen-sink\components\accordion'
 @ ./components/accordion/.content.xml 14:19-105
 @ ./.storybook/preview.js
 @ multi G:/aem-master/node_modules/@storybook/core/dist/server/common/polyfills.js G:/aem-master/node_modules/@storybook/core/dist/server/preview/globals.js G:/aem-master/node_modules/@storybook/addon-docs/dist/frameworks/common/config.js ./.storybook/preview.js G:/aem-master/node_modules/@storybook/addon-knobs/dist/preset/addDecorator.js ./.storybook/generated-entry.js (webpack)-hot-middleware/client.js?reload=true&quiet=false

ERROR in ./components/aemtext/.content.xml
Module not found: Error: Can't resolve 'G:aem-masterexamplesaem-kitchen-sinkcomponentsaemtext/' in 'G:\aem-master\examples\aem-kitchen-sink\components\aemtext'
 @ ./components/aemtext/.content.xml 4:29-10:5
 @ ./.storybook/preview.js
 @ multi G:/aem-master/node_modules/@storybook/core/dist/server/common/polyfills.js G:/aem-master/node_modules/@storybook/core/dist/server/preview/globals.js G:/aem-master/node_modules/@storybook/addon-docs/dist/frameworks/common/config.js ./.storybook/preview.js G:/aem-master/node_modules/@storybook/addon-knobs/dist/preset/addDecorator.js ./.storybook/generated-entry.js (webpack)-hot-middleware/client.js?reload=true&quiet=false

ERROR in ./components/list/.content.xml
Module not found: Error: Can't resolve 'G:aem-masterexamplesaem-kitchen-sinkcomponentslist/' in 'G:\aem-master\examples\aem-kitchen-sink\components\list'
 @ ./components/list/.content.xml 4:29-10:5
 @ ./.storybook/preview.js
 @ multi G:/aem-master/node_modules/@storybook/core/dist/server/common/polyfills.js G:/aem-master/node_modules/@storybook/core/dist/server/preview/globals.js G:/aem-master/node_modules/@storybook/addon-docs/dist/frameworks/common/config.js ./.storybook/preview.js G:/aem-master/node_modules/@storybook/addon-knobs/dist/preset/addDecorator.js ./.storybook/generated-entry.js (webpack)-hot-middleware/client.js?reload=true&quiet=false

ERROR in ./components/list/.content.xml
Module not found: Error: Can't resolve 'G:aem-masterexamplesaem-kitchen-sinkcomponentslist/list.html' in 'G:\aem-master\examples\aem-kitchen-sink\components\list'
 @ ./components/list/.content.xml 14:19-95
 @ ./.storybook/preview.js
 @ multi G:/aem-master/node_modules/@storybook/core/dist/server/common/polyfills.js G:/aem-master/node_modules/@storybook/core/dist/server/preview/globals.js G:/aem-master/node_modules/@storybook/addon-docs/dist/frameworks/common/config.js ./.storybook/preview.js G:/aem-master/node_modules/@storybook/addon-knobs/dist/preset/addDecorator.js ./.storybook/generated-entry.js (webpack)-hot-middleware/client.js?reload=true&quiet=false

ERROR in G:/aem-master/aem-sb-js-core-components/src/com/adobe/cq/wcm/core/components/models/List.js 10:15
Module parse failed: Unexpected token (10:15)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
|  */
| export default class List  {
>   static clazz = 'com.adobe.cq.wcm.core.components.models.List';
|
|   constructor(content) {
 @ G:/aem-master/aem-sb-js-core-components/models.js 12:50-111
 @ G:/aem-master/aem-sb-js-core-components/index.js
 @ ./.storybook/preview.js
 @ multi G:/aem-master/node_modules/@storybook/core/dist/server/common/polyfills.js G:/aem-master/node_modules/@storybook/core/dist/server/preview/globals.js G:/aem-master/node_modules/@storybook/addon-docs/dist/frameworks/common/config.js ./.storybook/preview.js G:/aem-master/node_modules/@storybook/addon-knobs/dist/preset/addDecorator.js ./.storybook/generated-entry.js (webpack)-hot-middleware/client.js?reload=true&quiet=false

ERROR in G:/aem-master/aem-sb-js-core-components/src/com/adobe/cq/wcm/core/components/models/Component.js 14:15
Module parse failed: Unexpected token (14:15)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
|    * @since com.adobe.cq.wcm.core.components.models 12.8.0
|    */
>   static PN_ID = "id";
|
|   /**
 @ G:/aem-master/aem-sb-js-core-components/models.js 7:55-121
 @ G:/aem-master/aem-sb-js-core-components/index.js
 @ ./.storybook/preview.js
 @ multi G:/aem-master/node_modules/@storybook/core/dist/server/common/polyfills.js G:/aem-master/node_modules/@storybook/core/dist/server/preview/globals.js G:/aem-master/node_modules/@storybook/addon-docs/dist/frameworks/common/config.js ./.storybook/preview.js G:/aem-master/node_modules/@storybook/addon-knobs/dist/preset/addDecorator.js ./.storybook/generated-entry.js (webpack)-hot-middleware/client.js?reload=true&quiet=false

ERROR in G:/aem-master/aem-sb-js-core-components/src/com/adobe/cq/wcm/core/components/models/Breadcrumb.js 15:24
Module parse failed: Unexpected token (15:24)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
|    * @since com.adobe.cq.wcm.core.components.models 11.1.0
|    */
>   static PN_SHOW_HIDDEN = "showHidden";
|
|   /**
 @ G:/aem-master/aem-sb-js-core-components/models.js 4:56-123
 @ G:/aem-master/aem-sb-js-core-components/index.js
 @ ./.storybook/preview.js
 @ multi G:/aem-master/node_modules/@storybook/core/dist/server/common/polyfills.js G:/aem-master/node_modules/@storybook/core/dist/server/preview/globals.js G:/aem-master/node_modules/@storybook/addon-docs/dist/frameworks/common/config.js ./.storybook/preview.js G:/aem-master/node_modules/@storybook/addon-knobs/dist/preset/addDecorator.js ./.storybook/generated-entry.js (webpack)-hot-middleware/client.js?reload=true&quiet=false

ERROR in G:/aem-master/aem-sb-js-core-components/src/com/adobe/cq/wcm/core/components/models/Teaser.js 15:30
Module parse failed: Unexpected token (15:30)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
|      * @since com.adobe.cq.wcm.core.components.models 12.4.0
|      */
>     static PN_ACTIONS_ENABLED = "actionsEnabled";
|
|     /**
 @ G:/aem-master/aem-sb-js-core-components/models.js 11:52-115
 @ G:/aem-master/aem-sb-js-core-components/index.js
 @ ./.storybook/preview.js
 @ multi G:/aem-master/node_modules/@storybook/core/dist/server/common/polyfills.js G:/aem-master/node_modules/@storybook/core/dist/server/preview/globals.js G:/aem-master/node_modules/@storybook/addon-docs/dist/frameworks/common/config.js ./.storybook/preview.js G:/aem-master/node_modules/@storybook/addon-knobs/dist/preset/addDecorator.js ./.storybook/generated-entry.js (webpack)-hot-middleware/client.js?reload=true&quiet=false

ERROR in G:/aem-master/aem-sb-js-core-components/src/com/adobe/cq/wcm/core/components/models/Container.js 18:37
Module parse failed: Unexpected token (18:37)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
|    * @since com.adobe.cq.wcm.core.components.models 12.8.0
|    */
>   static PN_BACKGROUND_IMAGE_ENABLED = "backgroundImageEnabled";
|
|   /**
 @ G:/aem-master/aem-sb-js-core-components/models.js 6:55-121
 @ G:/aem-master/aem-sb-js-core-components/index.js
 @ ./.storybook/preview.js
 @ multi G:/aem-master/node_modules/@storybook/core/dist/server/common/polyfills.js G:/aem-master/node_modules/@storybook/core/dist/server/preview/globals.js G:/aem-master/node_modules/@storybook/addon-docs/dist/frameworks/common/config.js ./.storybook/preview.js G:/aem-master/node_modules/@storybook/addon-knobs/dist/preset/addDecorator.js ./.storybook/generated-entry.js (webpack)-hot-middleware/client.js?reload=true&quiet=false

ERROR in G:/aem-master/aem-sb-js-core-components/src/com/adobe/cq/wcm/core/components/models/Image.js 18:44
Module parse failed: Unexpected token (18:44)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
|    * @since com.adobe.cq.wcm.core.components.models 11.0.0
|    */
>   static PN_DESIGN_ALLOWED_RENDITION_WIDTHS = "allowedRenditionWidths";
|
|   /**
 @ G:/aem-master/aem-sb-js-core-components/models.js 8:51-113
 @ G:/aem-master/aem-sb-js-core-components/index.js
 @ ./.storybook/preview.js
 @ multi G:/aem-master/node_modules/@storybook/core/dist/server/common/polyfills.js G:/aem-master/node_modules/@storybook/core/dist/server/preview/globals.js G:/aem-master/node_modules/@storybook/addon-docs/dist/frameworks/common/config.js ./.storybook/preview.js G:/aem-master/node_modules/@storybook/addon-knobs/dist/preset/addDecorator.js ./.storybook/generated-entry.js (webpack)-hot-middleware/client.js?reload=true&quiet=false

ERROR in G:/aem-master/aem-sb-js-core-components/src/com/adobe/cq/wcm/core/components/models/Button.js 2:17
Module parse failed: Unexpected token (2:17)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
| export default class Button {
>     static clazz = 'com.adobe.cq.wcm.core.components.models.Button';
|
|     constructor(content) {
 @ G:/aem-master/aem-sb-js-core-components/models.js 5:52-115
 @ G:/aem-master/aem-sb-js-core-components/index.js
 @ ./.storybook/preview.js
 @ multi G:/aem-master/node_modules/@storybook/core/dist/server/common/polyfills.js G:/aem-master/node_modules/@storybook/core/dist/server/preview/globals.js G:/aem-master/node_modules/@storybook/addon-docs/dist/frameworks/common/config.js ./.storybook/preview.js G:/aem-master/node_modules/@storybook/addon-knobs/dist/preset/addDecorator.js ./.storybook/generated-entry.js (webpack)-hot-middleware/client.js?reload=true&quiet=false

ERROR in G:/aem-master/aem-sb-js-core-components/src/com/adobe/cq/wcm/core/components/models/form/Button.js 2:17
Module parse failed: Unexpected token (2:17)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
| export default class Button {
>     static clazz = 'com.adobe.cq.wcm.core.components.models.form.Button';
|
|     constructor(content) {
 @ G:/aem-master/aem-sb-js-core-components/models.js 16:57-125
 @ G:/aem-master/aem-sb-js-core-components/index.js
 @ ./.storybook/preview.js
 @ multi G:/aem-master/node_modules/@storybook/core/dist/server/common/polyfills.js G:/aem-master/node_modules/@storybook/core/dist/server/preview/globals.js G:/aem-master/node_modules/@storybook/addon-docs/dist/frameworks/common/config.js ./.storybook/preview.js G:/aem-master/node_modules/@storybook/addon-knobs/dist/preset/addDecorator.js ./.storybook/generated-entry.js (webpack)-hot-middleware/client.js?reload=true&quiet=false

ERROR in G:/aem-master/aem-sb-js-core-components/src/com/adobe/cq/wcm/core/components/models/form/Text.js 2:17
Module parse failed: Unexpected token (2:17)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
| export default class Text {
>     static clazz = 'com.adobe.cq.wcm.core.components.models.form.Text';
|
|     constructor(content) {
 @ G:/aem-master/aem-sb-js-core-components/models.js 17:55-121
 @ G:/aem-master/aem-sb-js-core-components/index.js
 @ ./.storybook/preview.js
 @ multi G:/aem-master/node_modules/@storybook/core/dist/server/common/polyfills.js G:/aem-master/node_modules/@storybook/core/dist/server/preview/globals.js G:/aem-master/node_modules/@storybook/addon-docs/dist/frameworks/common/config.js ./.storybook/preview.js G:/aem-master/node_modules/@storybook/addon-knobs/dist/preset/addDecorator.js ./.storybook/generated-entry.js (webpack)-hot-middleware/client.js?reload=true&quiet=false

ERROR in G:/aem-master/aem-sb-js-core-components/src/com/adobe/cq/wcm/core/components/models/ListItem.js 7:15
Module parse failed: Unexpected token (7:15)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
|  */
| export default class ListItem {
>   static clazz = 'com.adobe.cq.wcm.core.components.models.ListItem';
|
|   constructor(content) {
 @ G:/aem-master/aem-sb-js-core-components/models.js 13:54-119
 @ G:/aem-master/aem-sb-js-core-components/index.js
 @ ./.storybook/preview.js
 @ multi G:/aem-master/node_modules/@storybook/core/dist/server/common/polyfills.js G:/aem-master/node_modules/@storybook/core/dist/server/preview/globals.js G:/aem-master/node_modules/@storybook/addon-docs/dist/frameworks/common/config.js ./.storybook/preview.js G:/aem-master/node_modules/@storybook/addon-knobs/dist/preset/addDecorator.js ./.storybook/generated-entry.js (webpack)-hot-middleware/client.js?reload=true&quiet=false

ERROR in G:/aem-master/aem-sb-js-core-components/src/com/adobe/cq/wcm/core/components/models/Text.js 7:15
Module parse failed: Unexpected token (7:15)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
|  */
| export default class Text {
>   static clazz = 'com.adobe.cq.wcm.core.components.models.Text';
|
|   constructor(content) {
 @ G:/aem-master/aem-sb-js-core-components/models.js 9:50-111
 @ G:/aem-master/aem-sb-js-core-components/index.js
 @ ./.storybook/preview.js
 @ multi G:/aem-master/node_modules/@storybook/core/dist/server/common/polyfills.js G:/aem-master/node_modules/@storybook/core/dist/server/preview/globals.js G:/aem-master/node_modules/@storybook/addon-docs/dist/frameworks/common/config.js ./.storybook/preview.js G:/aem-master/node_modules/@storybook/addon-knobs/dist/preset/addDecorator.js ./.storybook/generated-entry.js (webpack)-hot-middleware/client.js?reload=true&quiet=false

ERROR in G:/aem-master/aem-sb-js-core-components/src/com/adobe/cq/wcm/core/components/models/Title.js 7:15
Module parse failed: Unexpected token (7:15)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
|  */
| export default class Title {
>   static clazz = 'com.adobe.cq.wcm.core.components.models.Title';
|
|   constructor(content) {
 @ G:/aem-master/aem-sb-js-core-components/models.js 10:51-113
 @ G:/aem-master/aem-sb-js-core-components/index.js
 @ ./.storybook/preview.js
 @ multi G:/aem-master/node_modules/@storybook/core/dist/server/common/polyfills.js G:/aem-master/node_modules/@storybook/core/dist/server/preview/globals.js G:/aem-master/node_modules/@storybook/addon-docs/dist/frameworks/common/config.js ./.storybook/preview.js G:/aem-master/node_modules/@storybook/addon-knobs/dist/preset/addDecorator.js ./.storybook/generated-entry.js (webpack)-hot-middleware/client.js?reload=true&quiet=false

ERROR in G:/aem-master/aem-sb-js-core-components/src/com/adobe/cq/wcm/core/components/models/Separator.js 7:17
Module parse failed: Unexpected token (7:17)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
|  */
| export default class Separator {
>     static clazz = 'com.adobe.cq.wcm.core.components.models.Separator';
|
|     constructor(content) {
 @ G:/aem-master/aem-sb-js-core-components/models.js 15:55-121
 @ G:/aem-master/aem-sb-js-core-components/index.js
 @ ./.storybook/preview.js
 @ multi G:/aem-master/node_modules/@storybook/core/dist/server/common/polyfills.js G:/aem-master/node_modules/@storybook/core/dist/server/preview/globals.js G:/aem-master/node_modules/@storybook/addon-docs/dist/frameworks/common/config.js ./.storybook/preview.js G:/aem-master/node_modules/@storybook/addon-knobs/dist/preset/addDecorator.js ./.storybook/generated-entry.js (webpack)-hot-middleware/client.js?reload=true&quiet=false

ERROR in G:/aem-master/aem-sb-js-core-components/src/com/adobe/cq/wcm/core/components/models/ProgressBar.js 7:17
Module parse failed: Unexpected token (7:17)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
|  */
| export default class Text {
>     static clazz = 'com.adobe.cq.wcm.core.components.models.ProgressBar';
|
|     constructor(content) {
 @ G:/aem-master/aem-sb-js-core-components/models.js 14:57-125
 @ G:/aem-master/aem-sb-js-core-components/index.js
 @ ./.storybook/preview.js
 @ multi G:/aem-master/node_modules/@storybook/core/dist/server/common/polyfills.js G:/aem-master/node_modules/@storybook/core/dist/server/preview/globals.js G:/aem-master/node_modules/@storybook/addon-docs/dist/frameworks/common/config.js ./.storybook/preview.js G:/aem-master/node_modules/@storybook/addon-knobs/dist/preset/addDecorator.js ./.storybook/generated-entry.js (webpack)-hot-middleware/client.js?reload=true&quiet=false

ERROR in G:/aem-master/aem-sb-js-core-components/src/com/adobe/cq/wcm/core/components/models/Accordion.js 9:15
Module parse failed: Unexpected token (9:15)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
|  */
| export default class Accordion extends Container {
>   static clazz = 'com.adobe.cq.wcm.core.components.models.Accordion';
|
|   constructor(content) {
 @ G:/aem-master/aem-sb-js-core-components/models.js 3:55-121
 @ G:/aem-master/aem-sb-js-core-components/index.js
 @ ./.storybook/preview.js
 @ multi G:/aem-master/node_modules/@storybook/core/dist/server/common/polyfills.js G:/aem-master/node_modules/@storybook/core/dist/server/preview/globals.js G:/aem-master/node_modules/@storybook/addon-docs/dist/frameworks/common/config.js ./.storybook/preview.js G:/aem-master/node_modules/@storybook/addon-knobs/dist/preset/addDecorator.js ./.storybook/generated-entry.js (webpack)-hot-middleware/client.js?reload=true&quiet=false

ERROR in G:/aem-master/aem-sb-js-core-components/src/com/adobe/cq/wcm/core/components/models/Tabs.js 9:15
Module parse failed: Unexpected token (9:15)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
|  */
| export default class Tabs extends PanelContainer {
>   static clazz = 'com.adobe.cq.wcm.core.components.models.Tabs';
|
|   constructor(content) {
 @ G:/aem-master/aem-sb-js-core-components/models.js 18:50-111
 @ G:/aem-master/aem-sb-js-core-components/index.js
 @ ./.storybook/preview.js
 @ multi G:/aem-master/node_modules/@storybook/core/dist/server/common/polyfills.js G:/aem-master/node_modules/@storybook/core/dist/server/preview/globals.js G:/aem-master/node_modules/@storybook/addon-docs/dist/frameworks/common/config.js ./.storybook/preview.js G:/aem-master/node_modules/@storybook/addon-knobs/dist/preset/addDecorator.js ./.storybook/generated-entry.js (webpack)-hot-middleware/client.js?reload=true&quiet=false.............................

AND it goes on

**Expected behavior**

**Screenshots**

**Code snippets**
If applicable, add code samples to help explain your problem.

**System:**
Please paste the results of `npx -p @storybook/cli@next sb info` here.

**Additional context**

### PR DESCRIPTION
**Pull request by jzeltman**
Issue: Fixes #127 

## What I did
Updated the aem component and clientlib loaders to work with Windows

## How to test
Run on Windows and Mac

### CODE REVIEW

File: app/aem/src/server/aem-clientlib-txt-loader.js [hunk 1]
```diff
@@ -1,17 +1,17 @@
...
+const resolveDependencyFolder = (contextPath, source) => {
   const baseExpression = source.split(NEW_LINE).find(line => /^\s*#\s*base/.test(line));
   return contextPath + (baseExpression ? `/${extractBasePath(baseExpression)}` : '');
-}
+};
 
-function isAbsolutePath(path) {
-  return path.charAt(0) === '/';
-}
+const isAbsolutePath = filepath => filepath.charAt(0) === '/';
```
Comment (CodeByAlex) [inline app/aem/src/server/aem-clientlib-txt-loader.js:14]: Should we be using sep where we use slashes in the code?
