### PR TITLE
fix(runtime): add global properties

### LINKED ISSUE #90: 'properties' global varaible missing
in the sling htl engine, `properties` refers to the properties of the current resource.
this should also be available in storybook.

see: https://sling.apache.org/documentation/bundles/scripting/scripting-htl.html#global-objects

suggest to add all the global properties with meaningful default values:

| name             | sling type                                        | storybook type
|------------------|---------------------------------------------------|--------------|
| `currentNode`    | `javax.jcr.Node`                                  | current content object |
| `currentSession` | `javax.jcr.Session`                               | `NopProxy()` |
| `log`            | `org.slf4j.Logger`                                | `console` |
| `out`            | `java.io.PrintWriter`                             | `() => ()` |
| `properties`     | `org.apache.sling.api.resource.ValueMap`          | current content object |
| `reader`         | `java.io.BufferedReader`                          | `NopProxy()` |
| `request`        | `org.apache.sling.api.SlingHttpServletRequest`    | `NopProxy()` Note: this is quite important and we should provide a good request abstraction |
| `resolver`       | `org.apache.sling.api.resource.ResourceResolver`  | `NopProxy()` |
| `resource`       | `org.apache.sling.api.resource.Resource`          | current content object |
| `response`       | `org.apache.sling.api.SlingHttpServletResponse`   | `NopProxy()` |
| `sling`          | `org.apache.sling.api.scripting.SlingScriptHelper`| `NopProxy()` |

### PR DESCRIPTION
**Pull request by tripodsan**
fixes #90

## What I did
- added missing global properties
- added example story: 'globals'

### CODE REVIEW

**Comment by CodeByAlex** [comment]
@tripodsan, I'm a bit confused by this PR - what is it trying to achieve?

File: app/aem/src/client/preview/render.ts [hunk 1]
```diff
@@ -28,8 +29,40 @@ const createRuntime = (
 ) => {
   const models: Record<string, any> = aemMetadata ? aemMetadata.models : {};
   const components: any[] = aemMetadata ? aemMetadata.components : [];
+
+  const runtimeGlobals = {
```
Comment (jzeltman) [inline app/aem/src/client/preview/render.ts:33]: Could this be moved into another file to keep the render file smaller/cleaner?

**Comment by tripodsan** [comment]
@jzeltman can you re-review please?
